import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="min-h-full relative max-h-screen flex">
          <div className="flex flex-col min-h-screen w-full overflow-y-auto relative mx-4">
            {children}
          </div>
        </div>
      </body>
    </html>
  )
}
