import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import { Header } from './header'
import './globals.css'
import { SearchBar } from '@/widgets/search-bar'
import { Footer } from './footer'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="min-h-full relative max-h-screen flex">
          <div className="grid grid-rows-[auto_1fr_auto] min-h-screen w-full overflow-y-auto relative mx-4">
            <Header />
            <main className="flex flex-col gap-4">
              <SearchBar />
              {children}
            </main>
            <Footer />
          </div>
        </div>
      </body>
    </html>
  )
}
